/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserJFrames;

/**
 *
 * @author alber
 */
public class ExamineeHome extends javax.swing.JFrame {

    /**
     * Creates new form LoggedIn
     */
    public ExamineeHome(String accountName) {
        
        initComponents();
        accountLabel.setText(accountName + " (Examinee)");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loggedInLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        homeMenuBar = new javax.swing.JMenuBar();
        infoMenu = new javax.swing.JMenu();
        aboutItemMenu = new javax.swing.JMenuItem();
        contactMenuItem = new javax.swing.JMenuItem();
        creditsMenuItem = new javax.swing.JMenuItem();
        examMenu = new javax.swing.JMenu();
        takeExamMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loggedInLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        loggedInLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loggedInLabel.setText("You are now logged in as:");

        accountLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        accountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        infoMenu.setText("Info");

        aboutItemMenu.setText("About");
        aboutItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutItemMenuActionPerformed(evt);
            }
        });
        infoMenu.add(aboutItemMenu);

        contactMenuItem.setText("Contact");
        contactMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactMenuItemActionPerformed(evt);
            }
        });
        infoMenu.add(contactMenuItem);

        creditsMenuItem.setText("Credits");
        creditsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsMenuItemActionPerformed(evt);
            }
        });
        infoMenu.add(creditsMenuItem);

        homeMenuBar.add(infoMenu);

        examMenu.setText("Exam");

        takeExamMenuItem.setText("Take");
        takeExamMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeExamMenuItemActionPerformed(evt);
            }
        });
        examMenu.add(takeExamMenuItem);

        homeMenuBar.add(examMenu);

        setJMenuBar(homeMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loggedInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(loggedInLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aboutItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutItemMenuActionPerformed
        new About().setVisible(true);                             // Creates 'About' window and displays it
    }//GEN-LAST:event_aboutItemMenuActionPerformed

    private void contactMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactMenuItemActionPerformed
        new Contact().setVisible(true);
    }//GEN-LAST:event_contactMenuItemActionPerformed

    private void creditsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsMenuItemActionPerformed
        new Credits().setVisible(true);
    }//GEN-LAST:event_creditsMenuItemActionPerformed

    private void takeExamMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeExamMenuItemActionPerformed
        new TakeExam().setVisible(true);
    }//GEN-LAST:event_takeExamMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutItemMenu;
    private javax.swing.JLabel accountLabel;
    private javax.swing.JMenuItem contactMenuItem;
    private javax.swing.JMenuItem creditsMenuItem;
    private javax.swing.JMenu examMenu;
    private javax.swing.JMenuBar homeMenuBar;
    private javax.swing.JMenu infoMenu;
    private javax.swing.JLabel loggedInLabel;
    private javax.swing.JMenuItem takeExamMenuItem;
    // End of variables declaration//GEN-END:variables
}
