/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserJFrames.Examinees;

import java.io.*;
import java.nio.file.*;

public class TakeExam extends javax.swing.JFrame {

    /**
     * Creates new form TakeExam
     */
    public TakeExam(String accountName) {
        
        initComponents();
        nextButton.setEnabled(false);
        this.accountName = accountName;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorDialogLabel = new javax.swing.JLabel();
        questionAnswerInternalFrame = new javax.swing.JInternalFrame();
        questionLabel = new javax.swing.JLabel();
        answerRadioButton1 = new javax.swing.JRadioButton();
        answerRadioButton2 = new javax.swing.JRadioButton();
        answerRadioButton3 = new javax.swing.JRadioButton();
        answerRadioButton4 = new javax.swing.JRadioButton();
        nextButton = new javax.swing.JButton();
        quizNameLabel = new javax.swing.JLabel();
        quizNameTextField = new javax.swing.JTextField();
        confirmQuizNameButton = new javax.swing.JButton();
        topLabel = new javax.swing.JLabel();

        errorDialogLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        errorDialogLabel.setText("Please click the button that you think contains the correct answer before clicking 'Next'.");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        questionAnswerInternalFrame.setVisible(true);

        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        answerRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerRadioButton1ActionPerformed(evt);
            }
        });

        answerRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerRadioButton2ActionPerformed(evt);
            }
        });

        answerRadioButton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerRadioButton3ActionPerformed(evt);
            }
        });

        answerRadioButton4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout questionAnswerInternalFrameLayout = new javax.swing.GroupLayout(questionAnswerInternalFrame.getContentPane());
        questionAnswerInternalFrame.getContentPane().setLayout(questionAnswerInternalFrameLayout);
        questionAnswerInternalFrameLayout.setHorizontalGroup(
            questionAnswerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionAnswerInternalFrameLayout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addGroup(questionAnswerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(answerRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(answerRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answerRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answerRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(questionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        questionAnswerInternalFrameLayout.setVerticalGroup(
            questionAnswerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionAnswerInternalFrameLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(answerRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerRadioButton4)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        quizNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        quizNameLabel.setText("Quiz Name:");

        confirmQuizNameButton.setText("Confirm");
        confirmQuizNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmQuizNameButtonActionPerformed(evt);
            }
        });

        topLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        topLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quizNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quizNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmQuizNameButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(topLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(questionAnswerInternalFrame)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(topLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quizNameLabel)
                    .addComponent(quizNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmQuizNameButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionAnswerInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextButton)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
            
        // If the timer has not run out and no radio button has been selected
        
        if (quizTimer.isRunning() && answerSelected() == null) {
        
            quizTimer.stop();
            javax.swing.JOptionPane.showMessageDialog(this, errorDialogLabel, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            quizTimer.start();
            return;
        
        }
        
        checkAnswer();
        
        nextCounter++;
        
        if (nextCounter == allQuestions.size()) {
            
            saveScore();
            dispose();
            quizTimer.stop();
            new ReportSheet(correctAnswers, allQuestions.size()).setVisible(true);
            return;
            
        }
        
        questionLabel.setText(allQuestions.get(nextCounter)[0]);
        answerRadioButton1.setText(allQuestions.get(nextCounter)[1]);
        answerRadioButton2.setText(allQuestions.get(nextCounter)[2]);
        answerRadioButton3.setText(allQuestions.get(nextCounter)[3]);
        answerRadioButton4.setText(allQuestions.get(nextCounter)[4]);

        // Reset buttons
            
        resetRadioButtons();
        
        // Restart timer
        
        quizTimer.restart();
        incrementTimer.restart();
        
    }//GEN-LAST:event_nextButtonActionPerformed

    private void saveScore() {
    
        Path examineeQuizFolder = Paths.get(System.getProperty("user.home"), "QuizApplication", "Users", "Examinees", accountName, quizName);
            
        try {
            
            if (Files.notExists(examineeQuizFolder))
                Files.createDirectories(examineeQuizFolder);
            
        }
            
        catch(IOException x) {
            
            System.err.format("IOException: %s%n", x); 
            
        }
            
        try(BufferedWriter overwriteScore = Files.newBufferedWriter(examineeQuizFolder.resolve("score.log"), StandardOpenOption.CREATE);
                BufferedWriter overwriteAttempts = Files.newBufferedWriter(examineeQuizFolder.resolve("attempts.log"), StandardOpenOption.CREATE);
                BufferedReader readScore = Files.newBufferedReader(examineeQuizFolder.resolve("score.log"));
                BufferedReader readAttempts = Files.newBufferedReader(examineeQuizFolder.resolve("attempts.log"))) {
            
            double CorrectAnswersPercentage = (correctAnswers.doubleValue() / allQuestions.size()) * 100;
            String oldScore = readScore.readLine();
            if (oldScore == null || (CorrectAnswersPercentage > Double.parseDouble(oldScore)))
                overwriteScore.write(Double.toString(CorrectAnswersPercentage));
            
            String oldAttempts = readAttempts.readLine();
            if (oldAttempts == null)
                overwriteAttempts.write(Integer.toString(1));
            
            else {
            
                Integer newAttempts = Integer.parseInt(oldAttempts) + 1;
                overwriteAttempts.write(newAttempts.toString());
            
            }
        }
            
        catch(IOException x) {
            
            System.err.format("IOException: %s%n", x); 
            
        }
    }
    
    private void checkAnswer() {

        if (answerSelected() != null && answerSelected().equals(allQuestions.get(nextCounter)[5])) {
        
            correctAnswers++;
        
        }
    
    }
    
    private String answerSelected() {
    
        if (answerRadioButton1.isSelected()) {
        
            return answerRadioButton1.getText();
        
        }
        
        else if (answerRadioButton2.isSelected()) {
        
            return answerRadioButton2.getText();
        
        }
        
        else if (answerRadioButton3.isSelected()) {
        
            return answerRadioButton3.getText();
        
        }
        
        else if (answerRadioButton4.isSelected()) {
        
            return answerRadioButton4.getText();
        
        }
        
        else {
        
            return null;
        
        }
    
    }
    
    private void answerRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerRadioButton1ActionPerformed
        if (answerRadioButton1.isSelected())
            answerClicked(1);
        else
            answerUnclicked(1);
    }//GEN-LAST:event_answerRadioButton1ActionPerformed

    private void answerRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerRadioButton2ActionPerformed
        if (answerRadioButton2.isSelected())
            answerClicked(2);
        else
            answerUnclicked(2);
    }//GEN-LAST:event_answerRadioButton2ActionPerformed

    private void answerRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerRadioButton3ActionPerformed
        if (answerRadioButton3.isSelected())
            answerClicked(3);
        else
            answerUnclicked(3);
    }//GEN-LAST:event_answerRadioButton3ActionPerformed

    private void answerRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerRadioButton4ActionPerformed
        if (answerRadioButton4.isSelected())
            answerClicked(4);
        else
            answerUnclicked(4);
    }//GEN-LAST:event_answerRadioButton4ActionPerformed

    private void confirmQuizNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmQuizNameButtonActionPerformed
        
        if (quizNameTextField.getText().equals(""))
            return;
        
        quizName = quizNameTextField.getText();
        Path quizFolder = null;
        
        try {
        
            quizFolder = Paths.get(System.getProperty("user.home"), "QuizApplication", "Quizzes", quizName);
            if(Files.notExists(quizFolder)) {
            
                topLabel.setText("The quiz with the name you entered does not exist.");
                return;
            
            }
        }
        
        catch(InvalidPathException x) {
        
            topLabel.setText("The quiz name you entered is invalid. Please enter a valid quiz name.");
            return;
        
        }
        
        try (BufferedReader readQuantity = Files.newBufferedReader(quizFolder.resolve("quantity.log")); 
                BufferedReader readQuestions = Files.newBufferedReader(quizFolder.resolve("questions.log")); 
                BufferedReader readAnswers = Files.newBufferedReader(quizFolder.resolve("answers.log"))) {

            allQuestions = new java.util.ArrayList<String[]>(Integer.parseInt(readQuantity.readLine()));
            String[] eachQuestion = new String[6];
            String nextQuestion = readQuestions.readLine();
            
            while (nextQuestion != null) {
            
                eachQuestion[0] = nextQuestion;
                
                // Choices for the question
                
                eachQuestion[1] = readQuestions.readLine();
                eachQuestion[2] = readQuestions.readLine();
                eachQuestion[3] = readQuestions.readLine();
                eachQuestion[4] = readQuestions.readLine();
                
                // Correct answer for the question
                
                eachQuestion[5] = readAnswers.readLine();
                
                allQuestions.add(eachQuestion);
                
                eachQuestion = new String[6];                                   // Have to create new array object and assign it to eachQuestion variable, or else eachQuestion variable will reference the same array until the end of file
                nextQuestion = readQuestions.readLine();
            
            }
            
            java.util.Collections.shuffle(allQuestions);

        }
        
        catch (IOException x) {
        
            System.err.format("IOException: %s%n", x);
        
        }
        
        // Set up initial questions in window 
        
        questionLabel.setText(allQuestions.getFirst()[0]);
        answerRadioButton1.setText(allQuestions.getFirst()[1]);
        answerRadioButton2.setText(allQuestions.getFirst()[2]);
        answerRadioButton3.setText(allQuestions.getFirst()[3]);
        answerRadioButton4.setText(allQuestions.getFirst()[4]);
        
        topLabel.setText("");
        quizNameTextField.setEnabled(false);
        confirmQuizNameButton.setEnabled(false);
        nextButton.setEnabled(true);
        quizTimer = new javax.swing.Timer(10000, new java.awt.event.ActionListener() {
            
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            
                quizTimerActionPerformed(evt);
            
            }
            
        });
        
        
        incrementTimer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            
                incrementTimerActionPerformed(evt);
            
            }
            
        });
                
        topLabel.setText("Timer: " + Double.toString(quizTimer.getDelay() / (double) 1000));
        quizTimer.start();
        incrementTimer.start();
        
    }//GEN-LAST:event_confirmQuizNameButtonActionPerformed

    private void quizTimerActionPerformed(java.awt.event.ActionEvent evt) {

        incrementTimerCount = 0;
        quizTimer.stop();
        incrementTimer.stop();
        nextButtonActionPerformed(evt);

    }
    
    private void incrementTimerActionPerformed(java.awt.event.ActionEvent evt) {
    
        incrementTimerCount++;
        topLabel.setText("Timer: " + Double.toString((quizTimer.getDelay() / (double) 1000) - incrementTimerCount));
        incrementTimer.restart();
    
    }
    
    private void answerClicked(int answer) {
    
        switch(answer) {
            
            case 1:
                answerRadioButton2.setEnabled(false);
                answerRadioButton3.setEnabled(false);
                answerRadioButton4.setEnabled(false);
                break;
            case 2:
                answerRadioButton1.setEnabled(false);
                answerRadioButton3.setEnabled(false);
                answerRadioButton4.setEnabled(false);
                break;
            case 3:
                answerRadioButton1.setEnabled(false);
                answerRadioButton2.setEnabled(false);
                answerRadioButton4.setEnabled(false);
                break;
            default:
                answerRadioButton1.setEnabled(false);
                answerRadioButton2.setEnabled(false);
                answerRadioButton3.setEnabled(false);
                
        }
    
    }
    
    private void answerUnclicked(int answer) {
    
        switch(answer) {
            
            case 1:
                answerRadioButton2.setEnabled(true);
                answerRadioButton3.setEnabled(true);
                answerRadioButton4.setEnabled(true);
                break;
            case 2:
                answerRadioButton1.setEnabled(true);
                answerRadioButton3.setEnabled(true);
                answerRadioButton4.setEnabled(true);
                break;
            case 3:
                answerRadioButton1.setEnabled(true);
                answerRadioButton2.setEnabled(true);
                answerRadioButton4.setEnabled(true);
                break;
            default:
                answerRadioButton1.setEnabled(true);
                answerRadioButton2.setEnabled(true);
                answerRadioButton3.setEnabled(true);
                
        }
    
    }
    
    private void resetRadioButtons() {
    
        if (answerRadioButton1.isSelected()) {
        
            // Enable check boxes
            
            answerRadioButton2.setEnabled(true);
            answerRadioButton3.setEnabled(true);
            answerRadioButton4.setEnabled(true);
            
            // Deselect check box 1
            
            answerRadioButton1.setSelected(false);
        
        }
        
        else if (answerRadioButton2.isSelected()) {
        
            // Enable check boxes
            
            answerRadioButton1.setEnabled(true);
            answerRadioButton3.setEnabled(true);
            answerRadioButton4.setEnabled(true);
            
            // Deselect check box 2
            
            answerRadioButton2.setSelected(false);
            
        }
        
        else if (answerRadioButton3.isSelected()) {
        
            // Enable check boxes
            
            answerRadioButton1.setEnabled(true);
            answerRadioButton2.setEnabled(true);
            answerRadioButton4.setEnabled(true);
            
            // Deselect check box 3
            
            answerRadioButton3.setSelected(false);
        
        } 
        
        else {
        
            // Enable check boxes
            
            answerRadioButton1.setEnabled(true);
            answerRadioButton2.setEnabled(true);
            answerRadioButton3.setEnabled(true);
            
            // Deselect check box 4
            
            answerRadioButton4.setSelected(false);
        
        }
    }
    
    private int nextCounter = 0;
    private String quizName;
    java.util.ArrayList<String[]> allQuestions;
    private Integer correctAnswers = 0;
    String accountName;

    private javax.swing.Timer quizTimer;
    private javax.swing.Timer incrementTimer;
    int incrementTimerCount;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton answerRadioButton1;
    private javax.swing.JRadioButton answerRadioButton2;
    private javax.swing.JRadioButton answerRadioButton3;
    private javax.swing.JRadioButton answerRadioButton4;
    private javax.swing.JButton confirmQuizNameButton;
    private javax.swing.JLabel errorDialogLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JInternalFrame questionAnswerInternalFrame;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel quizNameLabel;
    private javax.swing.JTextField quizNameTextField;
    private javax.swing.JLabel topLabel;
    // End of variables declaration//GEN-END:variables
}
