/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserJFrames;

import java.io.*;
import java.nio.file.*;

public class CreateExam extends javax.swing.JFrame {

    /**
     * Creates new form ExamJFrame
     */
    public CreateExam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionAnswerInternalFrame = new javax.swing.JInternalFrame();
        questionTextField = new javax.swing.JTextField();
        answerTextField1 = new javax.swing.JTextField();
        answerTextField2 = new javax.swing.JTextField();
        answerTextField3 = new javax.swing.JTextField();
        answerTextField4 = new javax.swing.JTextField();
        questionLabel = new javax.swing.JLabel();
        answersLabel = new javax.swing.JLabel();
        answerCheckBox1 = new javax.swing.JCheckBox();
        answerCheckBox2 = new javax.swing.JCheckBox();
        answerCheckBox3 = new javax.swing.JCheckBox();
        answerCheckBox4 = new javax.swing.JCheckBox();
        nextButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        questionAnswerInternalFrame.setVisible(true);

        questionLabel.setText("Question");

        answersLabel.setText("Answers");

        answerCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerCheckBox1ActionPerformed(evt);
            }
        });

        answerCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerCheckBox2ActionPerformed(evt);
            }
        });

        answerCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerCheckBox3ActionPerformed(evt);
            }
        });

        answerCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerCheckBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout questionAnswerInternalFrameLayout = new javax.swing.GroupLayout(questionAnswerInternalFrame.getContentPane());
        questionAnswerInternalFrame.getContentPane().setLayout(questionAnswerInternalFrameLayout);
        questionAnswerInternalFrameLayout.setHorizontalGroup(
            questionAnswerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionAnswerInternalFrameLayout.createSequentialGroup()
                .addGroup(questionAnswerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionAnswerInternalFrameLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(questionLabel))
                    .addGroup(questionAnswerInternalFrameLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(answersLabel)))
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionAnswerInternalFrameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(questionAnswerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answerCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(answerCheckBox2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(answerCheckBox3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(answerCheckBox4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(questionAnswerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(answerTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(answerTextField4)
                    .addComponent(answerTextField3)
                    .addComponent(answerTextField2)
                    .addComponent(questionTextField))
                .addGap(44, 44, 44))
        );
        questionAnswerInternalFrameLayout.setVerticalGroup(
            questionAnswerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionAnswerInternalFrameLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(questionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answersLabel)
                .addGap(8, 8, 8)
                .addGroup(questionAnswerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(questionAnswerInternalFrameLayout.createSequentialGroup()
                        .addGroup(questionAnswerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answerCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answerTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(questionAnswerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answerTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answerCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answerTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(answerCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionAnswerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answerTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionAnswerInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(questionAnswerInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(nextButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishButton)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        
        Path questionsFile = Paths.get(System.getProperty("user.home"), "pass", "questions.log");
        
        try (BufferedWriter overwriteWriter = Files.newBufferedWriter(questionsFile, StandardOpenOption.CREATE, StandardOpenOption.WRITE);
                BufferedWriter appendWriter = Files.newBufferedWriter(questionsFile, StandardOpenOption.APPEND)) {
            
            overwriteWriter.write((++numQuestions).toString());
            overwriteWriter.newLine();
            overwriteWriter.flush();                                            // Makes sure all data written to overwriteWriter's buffer is put in the file, before the appendWriter begins writing data
            appendWriter.write(questionTextField.getText());
            appendWriter.newLine();
            appendWriter.write(answerTextField1.getText());
            appendWriter.newLine();
            appendWriter.write(answerTextField2.getText());
            appendWriter.newLine();
            appendWriter.write(answerTextField3.getText());
            appendWriter.newLine();
            appendWriter.write(answerTextField4.getText());
            appendWriter.newLine();
             
        } 
        
        catch(IOException x) {
        
            System.err.format("IOException: %s%n", x);
        
        }
        
        // Reset text and check boxes
        
        questionTextField.setText("");
        answerTextField1.setText("");
        answerTextField2.setText("");
        answerTextField3.setText("");
        answerTextField4.setText(""); 
        resetCheckBoxes();
        
    }//GEN-LAST:event_nextButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        dispose();
    }//GEN-LAST:event_finishButtonActionPerformed

    private void answerCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerCheckBox1ActionPerformed
        if (answerCheckBox1.isSelected())
            answerChecked(1);
        else
            answerUnchecked(1);
    }//GEN-LAST:event_answerCheckBox1ActionPerformed

    private void answerCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerCheckBox2ActionPerformed
        if (answerCheckBox2.isSelected())
            answerChecked(2);
        else
            answerUnchecked(2);
    }//GEN-LAST:event_answerCheckBox2ActionPerformed

    private void answerCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerCheckBox3ActionPerformed
        if (answerCheckBox3.isSelected())
            answerChecked(3);
        else
            answerUnchecked(3);
    }//GEN-LAST:event_answerCheckBox3ActionPerformed

    private void answerCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerCheckBox4ActionPerformed
        if (answerCheckBox4.isSelected())
            answerChecked(4);
        else
            answerUnchecked(4);
    }//GEN-LAST:event_answerCheckBox4ActionPerformed

    private void answerChecked(int answer) {
    
        switch(answer) {
            
            case 1:
                answerCheckBox2.setEnabled(false);
                answerCheckBox3.setEnabled(false);
                answerCheckBox4.setEnabled(false);
                break;
            case 2:
                answerCheckBox1.setEnabled(false);
                answerCheckBox3.setEnabled(false);
                answerCheckBox4.setEnabled(false);
                break;
            case 3:
                answerCheckBox1.setEnabled(false);
                answerCheckBox2.setEnabled(false);
                answerCheckBox4.setEnabled(false);
                break;
            default:
                answerCheckBox1.setEnabled(false);
                answerCheckBox2.setEnabled(false);
                answerCheckBox3.setEnabled(false);
                
        }
    
    }
    
    private void answerUnchecked(int answer) {
    
        switch(answer) {
            
            case 1:
                answerCheckBox2.setEnabled(true);
                answerCheckBox3.setEnabled(true);
                answerCheckBox4.setEnabled(true);
                break;
            case 2:
                answerCheckBox1.setEnabled(true);
                answerCheckBox3.setEnabled(true);
                answerCheckBox4.setEnabled(true);
                break;
            case 3:
                answerCheckBox1.setEnabled(true);
                answerCheckBox2.setEnabled(true);
                answerCheckBox4.setEnabled(true);
                break;
            default:
                answerCheckBox1.setEnabled(true);
                answerCheckBox2.setEnabled(true);
                answerCheckBox3.setEnabled(true);
                
        }
    
    }
    
    private void resetCheckBoxes() {
    
        if (answerCheckBox1.isSelected()) {
        
            // Enable check boxes
            
            answerCheckBox2.setEnabled(true);
            answerCheckBox3.setEnabled(true);
            answerCheckBox4.setEnabled(true);
            
            // Deselect check box 1
            
            answerCheckBox1.setSelected(false);
        
        }
        
        else if (answerCheckBox2.isSelected()) {
        
            // Enable check boxes
            
            answerCheckBox1.setEnabled(true);
            answerCheckBox3.setEnabled(true);
            answerCheckBox4.setEnabled(true);
            
            // Deselect check box 2
            
            answerCheckBox2.setSelected(false);
            
        }
        
        else if (answerCheckBox3.isSelected()) {
        
            // Enable check boxes
            
            answerCheckBox1.setEnabled(true);
            answerCheckBox2.setEnabled(true);
            answerCheckBox4.setEnabled(true);
            
            // Deselect check box 3
            
            answerCheckBox3.setSelected(false);
        
        } 
        
        else {
        
            // Enable check boxes
            
            answerCheckBox1.setEnabled(true);
            answerCheckBox2.setEnabled(true);
            answerCheckBox3.setEnabled(true);
            
            // Deselect check box 4
            
            answerCheckBox4.setSelected(false);
        
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateExam().setVisible(true);
            }
        });
    }

    private Integer numQuestions = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox answerCheckBox1;
    private javax.swing.JCheckBox answerCheckBox2;
    private javax.swing.JCheckBox answerCheckBox3;
    private javax.swing.JCheckBox answerCheckBox4;
    private javax.swing.JTextField answerTextField1;
    private javax.swing.JTextField answerTextField2;
    private javax.swing.JTextField answerTextField3;
    private javax.swing.JTextField answerTextField4;
    private javax.swing.JLabel answersLabel;
    private javax.swing.JButton finishButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JInternalFrame questionAnswerInternalFrame;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JTextField questionTextField;
    // End of variables declaration//GEN-END:variables
}
