/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserJFrames;

import java.io.*;
import java.nio.file.*;

public class TakeExam extends javax.swing.JFrame {

    /**
     * Creates new form TakeExam
     */
    public TakeExam() {
        
        initComponents();
        Path questionsFile = Paths.get(System.getProperty("user.home"), "QuizApplication", "Quizzes", "Quiz1", "questions.log");
        try (BufferedReader reader = Files.newBufferedReader(questionsFile)) {

            reader.readLine();                                      // Skip over first line
            questionLabel.setText(reader.readLine());
            answerRadioButton1.setText(reader.readLine());
            answerRadioButton2.setText(reader.readLine());
            answerRadioButton3.setText(reader.readLine());
            answerRadioButton4.setText(reader.readLine());

        }
        
        catch (IOException x) {
        
            System.err.format("IOException: %s%n", x);
        
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionAnswerInternalFrame = new javax.swing.JInternalFrame();
        questionLabel = new javax.swing.JLabel();
        answerRadioButton1 = new javax.swing.JRadioButton();
        answerRadioButton2 = new javax.swing.JRadioButton();
        answerRadioButton3 = new javax.swing.JRadioButton();
        answerRadioButton4 = new javax.swing.JRadioButton();
        nextButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        questionAnswerInternalFrame.setVisible(true);

        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        answerRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerRadioButton1ActionPerformed(evt);
            }
        });

        answerRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerRadioButton2ActionPerformed(evt);
            }
        });

        answerRadioButton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerRadioButton3ActionPerformed(evt);
            }
        });

        answerRadioButton4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout questionAnswerInternalFrameLayout = new javax.swing.GroupLayout(questionAnswerInternalFrame.getContentPane());
        questionAnswerInternalFrame.getContentPane().setLayout(questionAnswerInternalFrameLayout);
        questionAnswerInternalFrameLayout.setHorizontalGroup(
            questionAnswerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionAnswerInternalFrameLayout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addGroup(questionAnswerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(answerRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(answerRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answerRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answerRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(questionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        questionAnswerInternalFrameLayout.setVerticalGroup(
            questionAnswerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionAnswerInternalFrameLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(answerRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerRadioButton4)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionAnswerInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(questionAnswerInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        dispose();
    }//GEN-LAST:event_finishButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed

        Path questionsFile = Paths.get(System.getProperty("user.home"), "QuizApplication", "Quizzes", "Quiz1", "questions.log");
        try (BufferedReader reader = Files.newBufferedReader(questionsFile)) {
            
            nextCounter++;
            if (nextCounter == Integer.parseInt(reader.readLine()))             // reads first line of file and compares it to nextCounter
                dispose();
            
            // Skip questions and choices (for those questions) already given
            
            for (int i = 0; i < nextCounter * 5; i++) {
            
                reader.readLine(); 
            
            }
            
            questionLabel.setText(reader.readLine());
            answerRadioButton1.setText(reader.readLine());
            answerRadioButton2.setText(reader.readLine());
            answerRadioButton3.setText(reader.readLine());
            answerRadioButton4.setText(reader.readLine());

            // Reset buttons
            
            resetRadioButtons();
            
        }

        catch(IOException x) {

            System.err.format("IOException: %s%n", x);

        }
        
    }//GEN-LAST:event_nextButtonActionPerformed

    private void answerRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerRadioButton1ActionPerformed
        if (answerRadioButton1.isSelected())
            answerClicked(1);
        else
            answerUnclicked(1);
    }//GEN-LAST:event_answerRadioButton1ActionPerformed

    private void answerRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerRadioButton2ActionPerformed
        if (answerRadioButton2.isSelected())
            answerClicked(2);
        else
            answerUnclicked(2);
    }//GEN-LAST:event_answerRadioButton2ActionPerformed

    private void answerRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerRadioButton3ActionPerformed
        if (answerRadioButton3.isSelected())
            answerClicked(3);
        else
            answerUnclicked(3);
    }//GEN-LAST:event_answerRadioButton3ActionPerformed

    private void answerRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerRadioButton4ActionPerformed
        if (answerRadioButton4.isSelected())
            answerClicked(4);
        else
            answerUnclicked(4);
    }//GEN-LAST:event_answerRadioButton4ActionPerformed

    private void answerClicked(int answer) {
    
        switch(answer) {
            
            case 1:
                answerRadioButton2.setEnabled(false);
                answerRadioButton3.setEnabled(false);
                answerRadioButton4.setEnabled(false);
                break;
            case 2:
                answerRadioButton1.setEnabled(false);
                answerRadioButton3.setEnabled(false);
                answerRadioButton4.setEnabled(false);
                break;
            case 3:
                answerRadioButton1.setEnabled(false);
                answerRadioButton2.setEnabled(false);
                answerRadioButton4.setEnabled(false);
                break;
            default:
                answerRadioButton1.setEnabled(false);
                answerRadioButton2.setEnabled(false);
                answerRadioButton3.setEnabled(false);
                
        }
    
    }
    
    private void answerUnclicked(int answer) {
    
        switch(answer) {
            
            case 1:
                answerRadioButton2.setEnabled(true);
                answerRadioButton3.setEnabled(true);
                answerRadioButton4.setEnabled(true);
                break;
            case 2:
                answerRadioButton1.setEnabled(true);
                answerRadioButton3.setEnabled(true);
                answerRadioButton4.setEnabled(true);
                break;
            case 3:
                answerRadioButton1.setEnabled(true);
                answerRadioButton2.setEnabled(true);
                answerRadioButton4.setEnabled(true);
                break;
            default:
                answerRadioButton1.setEnabled(true);
                answerRadioButton2.setEnabled(true);
                answerRadioButton3.setEnabled(true);
                
        }
    
    }
    
    private void resetRadioButtons() {
    
        if (answerRadioButton1.isSelected()) {
        
            // Enable check boxes
            
            answerRadioButton2.setEnabled(true);
            answerRadioButton3.setEnabled(true);
            answerRadioButton4.setEnabled(true);
            
            // Deselect check box 1
            
            answerRadioButton1.setSelected(false);
        
        }
        
        else if (answerRadioButton2.isSelected()) {
        
            // Enable check boxes
            
            answerRadioButton1.setEnabled(true);
            answerRadioButton3.setEnabled(true);
            answerRadioButton4.setEnabled(true);
            
            // Deselect check box 2
            
            answerRadioButton2.setSelected(false);
            
        }
        
        else if (answerRadioButton3.isSelected()) {
        
            // Enable check boxes
            
            answerRadioButton1.setEnabled(true);
            answerRadioButton2.setEnabled(true);
            answerRadioButton4.setEnabled(true);
            
            // Deselect check box 3
            
            answerRadioButton3.setSelected(false);
        
        } 
        
        else {
        
            // Enable check boxes
            
            answerRadioButton1.setEnabled(true);
            answerRadioButton2.setEnabled(true);
            answerRadioButton3.setEnabled(true);
            
            // Deselect check box 4
            
            answerRadioButton4.setSelected(false);
        
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeExam().setVisible(true);
            }
        });
    }
    
    private int nextCounter = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton answerRadioButton1;
    private javax.swing.JRadioButton answerRadioButton2;
    private javax.swing.JRadioButton answerRadioButton3;
    private javax.swing.JRadioButton answerRadioButton4;
    private javax.swing.JButton finishButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JInternalFrame questionAnswerInternalFrame;
    private javax.swing.JLabel questionLabel;
    // End of variables declaration//GEN-END:variables
}
