package QuizApplicationPackage;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class About extends javax.swing.JFrame {

    /**
     * Creates new form AboutJFrame
     */
    public About() {
        
        initComponents();
        projectMembersInfo.add(JohnnyNicholson);
        projectMembersInfo.add(NathanGumataotao);
        projectMembersInfo.add(NolanSmith);
        projectMembersInfo.add(AlbertLehman);
        projectMembersInfo.add(EricLi);
        projectMembersInfo.add(JesusPelaez);
        projectMembersInfo.add(JesusMaciel);
        
        memberLabel.setText(projectMembersInfo.getFirst()[0]);
        educationPlaceholderLabel.setText(projectMembersInfo.getFirst()[1]);
        professionalSkillsPlaceholderLabel.setText(projectMembersInfo.getFirst()[2]);
        technicalSkillsPlaceholderLabel.setText(projectMembersInfo.getFirst()[3]);
        awardsRecognitionPlaceholderLabel.setText(projectMembersInfo.getFirst()[4]);
        workExperiencePlaceholderLabel.setText(projectMembersInfo.getFirst()[5]);
        
        previousButton.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        memberLabel = new javax.swing.JLabel();
        educationLabel = new javax.swing.JLabel();
        professionalSkillsLabel = new javax.swing.JLabel();
        technicalSkillsLabel = new javax.swing.JLabel();
        awardsRecognitionLabel = new javax.swing.JLabel();
        workExperienceLabel = new javax.swing.JLabel();
        educationPlaceholderLabel = new javax.swing.JLabel();
        professionalSkillsPlaceholderLabel = new javax.swing.JLabel();
        technicalSkillsPlaceholderLabel = new javax.swing.JLabel();
        awardsRecognitionPlaceholderLabel = new javax.swing.JLabel();
        workExperiencePlaceholderLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setText("Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        memberLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        memberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        educationLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        educationLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        educationLabel.setText("Education:");

        professionalSkillsLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        professionalSkillsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        professionalSkillsLabel.setText("Professional Skills:");

        technicalSkillsLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        technicalSkillsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        technicalSkillsLabel.setText("Technical Skills:");

        awardsRecognitionLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        awardsRecognitionLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        awardsRecognitionLabel.setText("Awards/Recognitions:");

        workExperienceLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        workExperienceLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        workExperienceLabel.setText("Relevant Work Experience, Internships, etc.:");

        educationPlaceholderLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        professionalSkillsPlaceholderLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        technicalSkillsPlaceholderLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        awardsRecognitionPlaceholderLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        workExperiencePlaceholderLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(previousButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(memberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(awardsRecognitionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(educationLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(professionalSkillsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(technicalSkillsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(workExperienceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(professionalSkillsPlaceholderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                            .addComponent(technicalSkillsPlaceholderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(awardsRecognitionPlaceholderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(workExperiencePlaceholderLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(educationPlaceholderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(memberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(educationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(educationPlaceholderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(professionalSkillsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(professionalSkillsPlaceholderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(technicalSkillsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(technicalSkillsPlaceholderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(awardsRecognitionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(awardsRecognitionPlaceholderLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workExperienceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workExperiencePlaceholderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(nextButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previousButton)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        
        memberLabel.setText(projectMembersInfo.get(index + 1)[0]);
        educationPlaceholderLabel.setText(projectMembersInfo.get(index + 1)[1]);
        professionalSkillsPlaceholderLabel.setText(projectMembersInfo.get(index + 1)[2]);
        technicalSkillsPlaceholderLabel.setText(projectMembersInfo.get(index + 1)[3]);
        awardsRecognitionPlaceholderLabel.setText(projectMembersInfo.get(index + 1)[4]);
        workExperiencePlaceholderLabel.setText(projectMembersInfo.get(index + 1)[5]);
        
        index++;
        
        switch(index) {
            
            case 1:
                previousButton.setEnabled(true);
                break;
            case 6:
                nextButton.setEnabled(false);
                
        }
        
    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        
        memberLabel.setText(projectMembersInfo.get(index - 1)[0]);
        educationPlaceholderLabel.setText(projectMembersInfo.get(index - 1)[1]);
        professionalSkillsPlaceholderLabel.setText(projectMembersInfo.get(index - 1)[2]);
        technicalSkillsPlaceholderLabel.setText(projectMembersInfo.get(index - 1)[3]);
        awardsRecognitionPlaceholderLabel.setText(projectMembersInfo.get(index - 1)[4]);
        workExperiencePlaceholderLabel.setText(projectMembersInfo.get(index - 1)[5]);
        
        index--;
        
        switch(index) {
           
            case 0:
                previousButton.setEnabled(false);
                break;
            case 5:
                nextButton.setEnabled(true);
                  
        }
        
    }//GEN-LAST:event_previousButtonActionPerformed
    
    private java.util.ArrayList<String[]> projectMembersInfo = new java.util.ArrayList<String[]>(7);
    
    private final String[] JohnnyNicholson = {
            
            "Johnny Nicholson", 
            "Third-year Computer Science Student", 
            "...", 
            "...", 
            "BSU leader, Faculty Assistant at Sacramento State Harper Alumni Center, KSSU Member", 
            "Shift-lead at Daiso"
            
    };
    
    private final String[] NathanGumataotao = {
        
            "Nathan Gumataotao",
            "Associates from Diablo Valley College, Sac State Undergraduate", 
            "Officer for Video Game Culture Club, Team for Video Game Culture Club", 
            "Proficient in C++, C#, Java, JavaScript, C, Can Operate Unix System, Blender, Unity, Algorithms", 
            "...", 
            "Ike's Love and Sandwiches - Line chef"
    
    };
    
    private final String[] NolanSmith = {
            
            "Nolan Smith", 
            "Associate Degree in Computer Science, Sac State Undergraduate", 
            "...", 
            "Competency in Java, C, C++, HTML, CSS, and JavaScript", 
            "...", 
            "..."
    
    };
    
    private final String[] AlbertLehman = {
        
            "Albert Lehman", 
            "San Joaquin Delta College, Sac State Undergraduate", 
            "...", 
            "Java, including the Java Swing framework", 
            "...", 
            "Teacher's Assistant"
    
    };
    
    private final String[] EricLi = {
        
        "Eric Li", 
        "CS Major at Sacramento State, Bachelor of CS in progress", 
        "...", 
        "Java, C, some C++, Associate", 
        "...", 
        "Walmart Stocking Associate (2022 - 2024)"
    
    };
    
    private final String[] JesusPelaez = {
        
        "Jesus Pelaez", 
        "Sac State Undergraduate", 
        "...", 
        "Java programmer, Assembly", 
        "...", 
        "Stockton Gaskets Assistant Manager/Manufacturer"
    
    };
    
    private final String[] JesusMaciel = {
        
        "Jesus Maciel", 
        "Sac State Undergraduate", 
        "...", 
        "...", 
        "...", 
        "..."};
    
    private int index = 0;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel awardsRecognitionLabel;
    private javax.swing.JLabel awardsRecognitionPlaceholderLabel;
    private javax.swing.JLabel educationLabel;
    private javax.swing.JLabel educationPlaceholderLabel;
    private javax.swing.JLabel memberLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JLabel professionalSkillsLabel;
    private javax.swing.JLabel professionalSkillsPlaceholderLabel;
    private javax.swing.JLabel technicalSkillsLabel;
    private javax.swing.JLabel technicalSkillsPlaceholderLabel;
    private javax.swing.JLabel workExperienceLabel;
    private javax.swing.JLabel workExperiencePlaceholderLabel;
    // End of variables declaration//GEN-END:variables
}
