/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuizApplicationPackage;

import static QuizApplicationPackage.User.error;
import static QuizApplicationPackage.User.loadNext;
import static QuizApplicationPackage.User.nonexistent;
import java.io.*;
import java.nio.file.*;

public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccountJFrame
     */
    public CreateAccount() {
        initComponents();
        
        setupAdminCheckbox();
    }
    
    private void setupAdminCheckbox() {
        
        // Allow administrator account if no administrator, otherwise explain why not.
        User admin = User.getAdministrator();
        if (admin == User.nonexistent) {
            administratorCheckBox.setEnabled(true);
        } else {
            ErrorLabel1.setText("Cannot create Administrator Account.");
            ErrorLabel2.setText((admin == User.error) ? "Error reading file to check for existing administrators." : "Administrator already exists.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordField = new javax.swing.JPasswordField();
        verifyPasswordField = new javax.swing.JPasswordField();
        accountTextField = new javax.swing.JTextField();
        accountLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        verifyPasswordLabel = new javax.swing.JLabel();
        ErrorPanel = new javax.swing.JPanel();
        ErrorLabel1 = new javax.swing.JLabel();
        ErrorLabel2 = new javax.swing.JLabel();
        ErrorPanel1 = new javax.swing.JPanel();
        createAccountButton = new javax.swing.JButton();
        administratorCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        passwordField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        passwordField.setMinimumSize(new java.awt.Dimension(160, 22));

        verifyPasswordField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        verifyPasswordField.setPreferredSize(new java.awt.Dimension(160, 22));

        accountTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        accountTextField.setActionCommand("<Not Set>");
        accountTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        accountTextField.setPreferredSize(new java.awt.Dimension(160, 22));

        accountLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        accountLabel.setText("Account Name");

        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordLabel.setText("Enter Password");

        verifyPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        verifyPasswordLabel.setText("Enter Password Again");

        ErrorLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ErrorLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ErrorLabel1.setText("");

        ErrorLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ErrorLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ErrorLabel2.setText("");

        javax.swing.GroupLayout ErrorPanelLayout = new javax.swing.GroupLayout(ErrorPanel);
        ErrorPanel.setLayout(ErrorPanelLayout);
        ErrorPanelLayout.setHorizontalGroup(
            ErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(ErrorPanelLayout.createSequentialGroup()
                .addGroup(ErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ErrorLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(ErrorLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ErrorPanelLayout.setVerticalGroup(
            ErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErrorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ErrorLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ErrorLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        createAccountButton.setText("Create");
        createAccountButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });

        /*
            Reversed so that checkbox is enabled only if an administrator is
            confirmed to not exist, because if instead it was disabled when an
            administrator is confirmed to exist, then it would remain enabled
            in the event of an error (such as when the file couldn't be opened)
            preventing administrator from being found, which would allow anyone
            to become administrator (bad).
        */
        administratorCheckBox.setEnabled(false);
        administratorCheckBox.setText("Administrator");
        
        setupAdminCheckbox();

        javax.swing.GroupLayout ErrorPanel1Layout = new javax.swing.GroupLayout(ErrorPanel1);
        ErrorPanel1.setLayout(ErrorPanel1Layout);
        ErrorPanel1Layout.setHorizontalGroup(
            ErrorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErrorPanel1Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(ErrorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(administratorCheckBox)
                    .addGroup(ErrorPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(createAccountButton)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        ErrorPanel1Layout.setVerticalGroup(
            ErrorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ErrorPanel1Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(administratorCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createAccountButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ErrorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ErrorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(verifyPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verifyPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifyPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verifyPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*
        Writes new user to file and returns a user that will "exist"
        (User.exist() == true) if and only if successful
    */
    User createAccount(String name, String password, User.Role role) {
        
        // Load account to determine its existence
        User existingUser = User.load(name);
        
        // If account already exists, unable to create account, return no new account
        if (User.exists(existingUser)) return null;
        
        // If account was otherwise not nonexistent (Error or somehow null), unable to determine if account exists, return error
        if (existingUser != User.nonexistent) return User.error;
        
        /* User is nonexistent, the new account can be created */
        
        /* Store account name and password entered by user into password file. Make sure to use the APPEND enum constant 
        so as to not overwrite the text that is already in the file. */
        
        try (BufferedWriter writer = Files.newBufferedWriter(User.accountsFile, StandardOpenOption.CREATE, StandardOpenOption.APPEND)) {
            
            writer.write(name);
            writer.newLine();
            writer.write(password);
            writer.newLine();
            writer.write(Integer.toString(role.getValue()));
            writer.newLine();
            
        } catch (IOException x) {
            System.err.format("IOException: %s%n", x);
            return User.error;
        }
        
        return new User(name, password, role);
    }
    
    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        
        // Retrieve all inputs
        String name = accountTextField.getText();
        String password = String.valueOf(passwordField.getPassword());
        String passwordVerification = String.valueOf(verifyPasswordField.getPassword());
        User.Role role = (administratorCheckBox.isSelected()) ? User.Role.ADMINISTRATOR : User.Role.EXAMINEE;
        
        // Determine whether the passwords entered in initial password field and the verify password field are the same
        if (!password.equals(passwordVerification)) {
        
            ErrorLabel1.setText("The given passwords do not match.");
            ErrorLabel2.setText("Please make sure they match.");
            return;
        }
        
        // Attempt to create account
        User user = createAccount(name, password, role);
        
        // Account already exists
        if (user == null) {
            ErrorLabel1.setText("An account with this name already exists.");
            ErrorLabel2.setText("Please chose a different name.");
            return;
        }
        
        // An error occured
        if (user == User.error) {
            ErrorLabel1.setText("An error occured while creating your account.");
            ErrorLabel2.setText("Account file not found or was formatted incorrectly.");
            return;
        }

        // Success
        dispose();     // Close the window                                                         
        
    }//GEN-LAST:event_createAccountButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorLabel1;
    private javax.swing.JLabel ErrorLabel2;
    private javax.swing.JPanel ErrorPanel;
    private javax.swing.JPanel ErrorPanel1;
    private javax.swing.JLabel accountLabel;
    private javax.swing.JTextField accountTextField;
    private javax.swing.JCheckBox administratorCheckBox;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField verifyPasswordField;
    private javax.swing.JLabel verifyPasswordLabel;
    // End of variables declaration//GEN-END:variables
}
