package QuizApplicationPackage;

import javax.swing.*;
import java.net.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class Login extends javax.swing.JFrame
{

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JLabel accountNameLabel;
    private javax.swing.JTextField accountTextField;
    private javax.swing.JMenuItem contactMenuItem;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JLabel createAccountLabel1;
    private javax.swing.JLabel createAccountLabel2;
    private javax.swing.JPanel createAccountPanel;
    private javax.swing.JMenuItem creditsMenuItem;
    private javax.swing.JMenuBar homeMenuBar;
    private javax.swing.JMenu infoMenu;
    private javax.swing.JMenu socialmediaMenu;              // Social Media drop down menu for clickable links
        // Menu Buttons for Social Media Menu
    private javax.swing.JMenuItem instagramMenuItem;
    private javax.swing.JMenuItem githubMenuItem;
    private javax.swing.JMenuItem blueskyMenuItem;
    private javax.swing.JMenuItem xMenuItem;
    private javax.swing.JMenuItem linkedinMenuItem;
        //
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form HomeJFrame
     */
    public Login()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        createAccountPanel = new javax.swing.JPanel();
        createAccountLabel1 = new javax.swing.JLabel();
        createAccountLabel2 = new javax.swing.JLabel();
        createAccountButton = new javax.swing.JButton();
        accountNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        accountTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();
        homeMenuBar = new javax.swing.JMenuBar();
        infoMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        contactMenuItem = new javax.swing.JMenuItem();
        creditsMenuItem = new javax.swing.JMenuItem();
        socialmediaMenu = new javax.swing.JMenu();
        instagramMenuItem = new javax.swing.JMenuItem();
        githubMenuItem = new javax.swing.JMenuItem();
        blueskyMenuItem = new javax.swing.JMenuItem();
        xMenuItem = new javax.swing.JMenuItem();
        linkedinMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));

        createAccountLabel1.setText("Don't have an account?");

        createAccountLabel2.setText("Click the 'Create Account' button below.");

        createAccountButton.setText("Create Account");
        createAccountButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                createAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createAccountPanelLayout = new javax.swing.GroupLayout(createAccountPanel);
        createAccountPanel.setLayout(createAccountPanelLayout);
        createAccountPanelLayout.setHorizontalGroup(
                createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(createAccountPanelLayout.createSequentialGroup()
                                .addContainerGap(128, Short.MAX_VALUE)
                                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAccountPanelLayout.createSequentialGroup()
                                                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(createAccountLabel2)
                                                        .addGroup(createAccountPanelLayout.createSequentialGroup()
                                                                .addComponent(createAccountButton)
                                                                .addGap(50, 50, 50)))
                                                .addGap(67, 67, 67))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAccountPanelLayout.createSequentialGroup()
                                                .addComponent(createAccountLabel1)
                                                .addGap(113, 113, 113))))
        );
        createAccountPanelLayout.setVerticalGroup(
                createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(createAccountPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(createAccountLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(createAccountLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(createAccountButton)
                                .addContainerGap())
        );

        accountNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        accountNameLabel.setText("Account Name");

        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        passwordLabel.setText("Enter Password");

        passwordField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                passwordFieldActionPerformed(evt);
            }
        });

        loginButton.setText("Log in");
        loginButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loginButtonActionPerformed(evt);
            }
        });

        ErrorLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        infoMenu.setText("Info");

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aboutMenuItemActionPerformed(evt);
            }
        });
        infoMenu.add(aboutMenuItem);

        contactMenuItem.setText("Contact");
        contactMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                contactMenuItemActionPerformed(evt);
            }
        });
        infoMenu.add(contactMenuItem);

        creditsMenuItem.setText("Credits");
        creditsMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                creditsMenuItemActionPerformed(evt);
            }
        });
        infoMenu.add(creditsMenuItem);

        socialmediaMenu.setText("Social Media");
        socialmediaMenu.add(instagramMenuItem);
        socialmediaMenu.add(githubMenuItem);
        socialmediaMenu.add(blueskyMenuItem);
        socialmediaMenu.add(xMenuItem);
        socialmediaMenu.add(linkedinMenuItem);

        // Listeners for each of the social media buttons
        setSocialMediaIcon(instagramMenuItem,"icons/ig.png", "Instagram");
        instagramMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                instagramMenuItemActionPerformed(evt);
            }
        });

        setSocialMediaIcon(githubMenuItem,"icons/github.png", "Github");
        githubMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                githubMenuItemActionPerformed(evt);
            }
        });

        setSocialMediaIcon(blueskyMenuItem,"icons/bluesky.png", "BlueSky");
        blueskyMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                blueskyMenuItemActionPerformed(evt);
            }
        });

        setSocialMediaIcon(xMenuItem,"icons/x.png", "X");
        xMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                xMenuItemActionPerformed(evt);
            }
        });

        setSocialMediaIcon(linkedinMenuItem,"icons/linkedin.png", "LinkedIn");
        linkedinMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                linkedinMenuItemActionPerformed(evt);
            }
        });

        homeMenuBar.add(infoMenu);
        homeMenuBar.add(socialmediaMenu);
        setJMenuBar(homeMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(141, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(189, 189, 189)
                                                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passwordField)))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(accountNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(accountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(createAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(87, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(accountNameLabel)
                                        .addComponent(accountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_createAccountButtonActionPerformed
        new CreateAccount().setVisible(true);
    }//GEN-LAST:event_createAccountButtonActionPerformed    

    // Returns null if unsuccessful
    private User attemptLogin(String name, String password)
    {

        // If user is found and password matches, return user
        User user = User.load(name);
        if (User.exists(user) && user.hasPassword(password)) return user;

        // Could not log in
        return null;
    }

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_passwordFieldActionPerformed

        // Recieve input from fields
        String name = accountTextField.getText();
        ;
        String password = String.valueOf(passwordField.getPassword());

        // Attempt to log in with input
        User user = attemptLogin(name, password);

        if (user == null)
        {
            ErrorLabel.setText("No account with a matching username and password was found.");
            return;
        }

        // Open corresponding Home page
        switch (user.getRole())
        {
            case User.Role.EXAMINEE:
                new Examinees.Home(user.name).setVisible(true);
                break;
            case User.Role.ADMINISTRATOR:
                new Administrator.Home(user.name).setVisible(true);
                break;
            default:
                // Role unaccounted for
                break;
        }

    }//GEN-LAST:event_passwordFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        passwordFieldActionPerformed(evt);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void creditsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsMenuItemActionPerformed
        new Credits().setVisible(true);
    }//GEN-LAST:event_creditsMenuItemActionPerformed

    private void contactMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactMenuItemActionPerformed
        new Contact().setVisible(true);
    }//GEN-LAST:event_contactMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new About().setVisible(true);                             // Creates 'About' window and displays it
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void instagramMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        openLink("https://www.instagram.com/project_hotel_csc131/");
    }

    private void githubMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        openLink("https://github.com/albert-l30/CSC131Project");
    }

    private void blueskyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        openLink("https://bsky.app/profile/projecthotel131.bsky.social");
    }

    private void xMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        openLink("https://x.com/ProjectHotel131");
    }

    private void linkedinMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        openLink("https://www.linkedin.com/in/project-hotel-a94880362/");
    }
    // Function used to open a link from the desktop's default browser
    public static void openLink(String url) {
        try {
            java.awt.Desktop.getDesktop().browse(URI.create(url));
        } catch (java.io.IOException e){}
    }
    public static void setSocialMediaIcon(JMenuItem menuItem, String directory, String socialmediaName) {
        try {
            menuItem.setIcon(new ImageIcon(Login.class.getResource(directory)));
        }
        catch (NullPointerException x) {
            JOptionPane.showMessageDialog(
                    null,
                    socialmediaName + " icon could not be loaded: " + x.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            menuItem.setText(socialmediaName);
        }
    }
}



