/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Examinees;

import QuizApplicationPackage.User;
import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.WindowConstants;

public class Grades extends javax.swing.JFrame {

    /** Creates new form Grades
    * @param userName
    */
    public Grades(String userName) {
        initComponents();
        
        // Correct initComponents' alterations
        BoxLayout layout = new BoxLayout(getContentPane(), BoxLayout.Y_AXIS);
        getContentPane().setLayout(layout);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        setSize(720, 640);
        
        listGrades(userName);
    }
    
    private static final Path quizzesDirectory = Paths.get(System.getProperty("user.home"), "QuizApplication", "Quizzes");
    
    private void listGrades(String userName) {
        
        // Prepare container and label
        
        JFrame frame = this;
        
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        
        JLabel label = new JLabel(userName + "'s Grades:");
        label.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        panel.add(label);
        
        // Find and display each quiz, with report sheet if possible.
        
        File quizzesFolder = new File(quizzesDirectory.toString());
        File[] quizFolders = quizzesFolder.listFiles();
        
        if (quizFolders == null) return;
        
        for (File quizFolder : quizFolders) {
            
            String quizName = quizFolder.getName();
            
            ReportSheet reportSheet = ReportSheet.load(userName, quizName);
            
            String score = "N/A";
            if (reportSheet != null) score = (reportSheet.calculateScoreRatio() * 100.0d) + " %";
            
            // Panel to contain Exam
            JPanel examPanel = new JPanel();
            examPanel.setBorder(BorderFactory.createLineBorder(Color.black));
            
            // Label to display Exam name and score
            JLabel nameLabel = new JLabel(quizName + " (Score: " + score + ")");
            examPanel.add(nameLabel);
                
            // Button to view Report Sheet if exists
            if (reportSheet != null) {
                JButton reportSheetButton = new JButton("View Report Sheet");
                
                reportSheetButton.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        new ReportSheetDisplay(reportSheet).setVisible(true);
                    }
                });
                
                examPanel.add(reportSheetButton);
            }
                
                // Try to make the panels not take up the entire screen
                {
                    // An arbitrarily large width so that the maximum height can be set
                    int panelWidth = 10000;
                    
                    // The maximum height
                    int panelHeight = 50;
                    
                    examPanel.setSize(new Dimension(examPanel.getSize().width, panelHeight));
                    examPanel.setPreferredSize(new Dimension(examPanel.getSize().width, panelHeight));
                    examPanel.setMaximumSize(new Dimension(panelWidth, panelHeight));
                }
                
                panel.add(examPanel);
        }

        JScrollPane scroll = new JScrollPane(panel);
        frame.add(scroll);
        frame.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ///**
    // * @param args the command line arguments
    // */
    //public static void main(String args[]) {
    //    /* Set the Nimbus look and feel */
    //    /* Create and display the form */
    //    java.awt.EventQueue.invokeLater(new Runnable() {
    //        public void run() {
    //            new Grades("accname").setVisible(true);
    //        }
    //    });
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
