/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrator;

import QuizApplicationPackage.*;

/**
 *
 * @author alber
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form AdministratorHome
     */
    public Home(String accountName) {
        
        initComponents();
        accountLabel.setText(accountName + " (Administrator)");
        
        
        viewExamineesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserList userList = new UserList();
                userList.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loggedInLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        homeMenuBar = new javax.swing.JMenuBar();
        infoMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        contactMenuItem = new javax.swing.JMenuItem();
        creditsMenuItem = new javax.swing.JMenuItem();
        examMenu = new javax.swing.JMenu();
        createExamMenuItem = new javax.swing.JMenuItem();
        modifyExamMenuItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        viewExamineesMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loggedInLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        loggedInLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loggedInLabel.setText("You are now logged in as:");

        accountLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        accountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        infoMenu.setText("Info");

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        infoMenu.add(aboutMenuItem);

        contactMenuItem.setText("Contact");
        contactMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactMenuItemActionPerformed(evt);
            }
        });
        infoMenu.add(contactMenuItem);

        creditsMenuItem.setText("Credits");
        creditsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsMenuItemActionPerformed(evt);
            }
        });
        infoMenu.add(creditsMenuItem);

        homeMenuBar.add(infoMenu);

        examMenu.setText("Exam");

        createExamMenuItem.setText("Create");
        createExamMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createExamMenuItemActionPerformed(evt);
            }
        });
        examMenu.add(createExamMenuItem);

        modifyExamMenuItem.setText("Modify");
        modifyExamMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyExamMenuItemActionPerformed(evt);
            }
        });
        examMenu.add(modifyExamMenuItem);

        homeMenuBar.add(examMenu);

        viewMenu.setText("View");

        viewExamineesMenuItem.setText("Examinees");
        viewMenu.add(viewExamineesMenuItem);

        homeMenuBar.add(viewMenu);

        setJMenuBar(homeMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loggedInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(loggedInLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new About().setVisible(true);                             // Creates 'About' window and displays it
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void contactMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactMenuItemActionPerformed
        new Contact().setVisible(true);
    }//GEN-LAST:event_contactMenuItemActionPerformed

    private void creditsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsMenuItemActionPerformed
        new Credits().setVisible(true);
    }//GEN-LAST:event_creditsMenuItemActionPerformed

    private void createExamMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createExamMenuItemActionPerformed
        new CreateExam().setVisible(true);
    }//GEN-LAST:event_createExamMenuItemActionPerformed

    private void modifyExamMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyExamMenuItemActionPerformed
        new ModifyExam().setVisible(true);
    }//GEN-LAST:event_modifyExamMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JLabel accountLabel;
    private javax.swing.JMenuItem contactMenuItem;
    private javax.swing.JMenuItem createExamMenuItem;
    private javax.swing.JMenuItem creditsMenuItem;
    private javax.swing.JMenu examMenu;
    private javax.swing.JMenuBar homeMenuBar;
    private javax.swing.JMenu infoMenu;
    private javax.swing.JLabel loggedInLabel;
    private javax.swing.JMenuItem modifyExamMenuItem;
    private javax.swing.JMenuItem viewExamineesMenuItem;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}
